name = "kempingi"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "kempingi-prod"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[vars]
SITE_URL = "https://kempingi.com"
NODE_ENV = "production"
